### ISSUE TITLE
Variable shadowing

### ISSUE THREAD

**Issue by zuiderkwast** [josefs/Gradualizer#138]
To implement shadowing we need nested variable scopes.

Shadowing can happen for (nested) funs and comprehensions. Other clauses (case, receive, try-of, catch) don't introduce scope.

Examples:
```Erlang
-spec f(boolean(), [integer()]) -> [integer()].
f(X, Xs) ->
    [X || X <- Xs].

-spec g(string()) -> integer().
g(X) ->
    (fun(X) -> X + 2 end)(list_to_integer(X)).
```

**Comment by SimSmith** [comment]
Correct me if I am wrong but Gradualizer cannot handle anonymous functions (nested funs) at all.

For example:
```erlang
-spec f(list()) -> binary().
f(Int) ->
    F = fun(I) -> integer_to_binary(I) end,
    F(Int).
```
This will pass even though the spec is wrong, because we hid the `interger_to_binary/1` in an anonymous function

**Comment by gomoripeti** [comment]
@SimSmith Gradualizer can infer the return type of anonymous functions. In this example it infers the return type of `F` from the spec of `integer_to_binary/1` to be `binary()`. And that matches the declared return type of `f/1`. It also infers the arity of `F` (that's not a big magic).
What Gradualizer cannot do currently is to infer type of the arguments of `F`. It will infer `fun( (any()) -> binary() )` only. This is on the TODO list.

**Comment by SimSmith** [comment]
> @SimSmith Gradualizer can infer the return type of anonymous functions.

@gomoripeti Yes, but it's not always successful at that. An example is an anonymous identity function or this:
```erlang
-spec f() -> list().
f() ->
    F = fun() -> 42 end,
    F().
```

**Comment by gomoripeti** [comment]
This is intentional. The wiki is work-in-progress but it has some basic information about [bidirectional type checking](https://github.com/josefs/Gradualizer/wiki/Bidirectional-type-checking) and [type inference](https://github.com/josefs/Gradualizer/wiki/Type-inference) in Gradualizer.

The essence is that by default only expressions that contain a call to a function with a spec has a type inferred. This is in order so that fully untyped (no-spec) programs always pass type checking. And this way to allow the user to have full control.

You can change this behaviour with the `--infer` flag.

Of course even with this flag Gradulaizer might not always be successful (bug or missing feature), please reports such cases!

**Comment by josefs** [comment]
@zuiderkwast, what do you mean when you say:

> To implement shadowing we need nested variable scopes.

Gradualizer does handle nested scopes right now. There are the odd bugs as you've discovered but I believe those should be relatively easily fixed.

**Comment by zuiderkwast** [comment]
The examples I added are not odd bugs but just examples of shadowing. Perhaps this is a better example:

```Erlang
-spec f(X :: [integer()]) -> [integer()].
f(X) ->
    Succ = fun(X) ->
                   %% here X is a number. The outer X is shadowed.
                   X + 1
           end,
    %% here, X is a list again
    lists:map(Succ, X).
```

When a variable gets out of scope, the outer variable is unshadowed again. We need to get back the VEnv from before the fun expression. Any constraints on the inner X and the outer X should be kept apart as well. I don't think we handle this now.

Currently, on the line `Succ = fun(X) ->`, the type checker considers X bound, just as if the fun expression would be a case expression. In a fun clause head, all variables should be considered free. We don't distinguish between fun clauses and case clauses, but we should.

The VEnv which is passed around is a map `#{VariableName => Type}`. With nested scopes I mean that we need a list of such maps, but perhaps there are other ways...

**Comment by josefs** [comment]
We don't need a list of maps to handle scope. The way I've implemented scope handling in the Gradualizer can be outlined as follows:

- For "normal" scope handling I've used the standard technique of having different environment for different scopes. This is just like functional programming. When you enter a new scope and bind a variable, a new environment is created from the old one, where the newly bound variable is added. We restore the old scope by simply reusing the old environment and throwing away the new one.
- To accommodate for Erlangs weird scoping where a variable occurrence can cause it to come into scope in its enclosing expression, every type checking function returns a set of variables which were brought into scope in that expression. These have to be added to the environment at appropriate places to make sure we adhere to Erlangs scoping. Note that I've taken care to throw away these returned variables for funs, since funs actually delimit the scope.

I hope that explanation helps.

**Comment by zuiderkwast** [comment]
Thanks! Yes, this makes sense.

It seems the only problem is this TODO in [typechecker.erl#L3192](https://github.com/josefs/Gradualizer/blob/master/src/typechecker.erl#L3192) then:

```Erlang
add_type_pat({var, _, A} = Var, Ty, TEnv, VEnv) ->
    %% TODO: In a fun clause, A is always free, but not in e.g. case clauses
    case VEnv of
        #{A := VarTy} ->
            case subtype(VarTy, Ty, TEnv) of
                {true, Cs} ->
                    {type(none), VarTy, VEnv, Cs};
                false ->
                    throw({type_error, Var, VarTy, Ty})
            end;
        _FreeVar ->
            {Ty, Ty, VEnv#{A => Ty}, constraints:empty()}
end;
```

**Comment by josefs** [comment]
Good catch! We will need to pass some information about what context the pattern comes from. Do you feel like tackling it, @zuiderkwast?

**Comment by zuiderkwast** [comment]
"Pass some information" sounds like a good idea. :-) I don't want to tackle it right now though. Perhaps another day.

I think it's not extremely urgent for the beta release because the compiler gives a warning for shadowing. This kind of makes people avoid shadowing. What do you think?

**Comment by josefs** [comment]
What I meant with "pass some information" was really just an atom, either `case` or `fun`. That should be enough, I think.

I agree that this might not be super important for a beta release.
