### ISSUE TITLE
Binary patterns and Elixir.String.t

### ISSUE THREAD

**Issue by mbuhot** [josefs/Gradualizer#16]
Hello, thanks for creating Gradualizer!
I tried it out on a simple module and ran into this error:

```elixir
# foo.ex
defmodule Foo do
  @spec is_comment?(String.t()) :: boolean
  def is_comment?("#" <> _rest), do: true
  def is_comment?(_), do: false
end
```

```bash
iex(4)> :gradualizer.type_check_module(Foo)
The pattern <<"#",_rest@1/binary>> on line 3 doesn't have the type 'Elixir.String':t()
:nok
```

Looks like it hasn't resolved the type `Elixir.String.t` as a synonym for `binary` ?

**Comment by josefs** [comment]
The gradualizer currently doesn't know anything about Elixir. But it would be really nice to support it! Patches are welcome. 
@tim2CF do you have any thoughts on this?

**Comment by tim2CF** [comment]
Hello!
I'll take a look on this week :)

**Comment by zuiderkwast** [comment]
Hi! I have added two commits for binaries/bitstrings (70a42c225857d7ec0964835191d594d9f7806723 subtype relation and 37399e4abd9bc1de9cdd9f84f4aa4ab4a7846772 type checking bit expressions and patterns). Perhaps this helps a bit? It is not really well-tested yet...

**Comment by josefs** [comment]
@mbuhot, I believe we've added the support needed for your program to go through Gradualizer. Can you confirm?

**Comment by josefs** [comment]
@mbuhot, thanks for your quick feedback! The error message that you get now is rather puzzling to me but we don't have anyone working on Elixir support so I'm afraid it won't be investigated any time soon. So I'll close this ticket then.

The comment that you pointed to turned out to be outdated and I've updated the test case to reflect that.
