### ISSUE TITLE
Cannot compile Gradualizer

### ISSUE THREAD

**Issue by aleklisi** [josefs/Gradualizer#196]
I am using Erlang OTP 22.0.7
```
erl -version
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.4.4
```
```
erl
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Eshell V10.4.4  (abort with ^G)
1> erlang:system_info(otp_release).
"22"
```

I cloned your repo and tried `make escript` on the master branch. So I run:

```
make escript
rebar3 escriptize
===> Verifying dependencies...
===> Compiling gradualizer
===> Compiling src/gradualizer_prelude.erl failed
src/gradualizer_prelude.erl:none: error in parse transform 'gradualizer_prelude_parse_trans': {undef,
                                                             [{gradualizer_file_utils,
                                                               get_forms_from_erl,
                                                               ["/Users/aleksanderlisiecki/Documents/Github/Gradualizer/_build/default/lib/gradualizer/priv/prelude/application.specs.erl",
                                                                []],
                                                               []},
                                                              {gradualizer_prelude_parse_trans,
                                                               get_module_and_forms,
                                                               1,
                                                               [{file,
                                                                 "/Users/aleksanderlisiecki/Documents/Github/Gradualizer/src/gradualizer_prelude_parse_trans.erl"},
                                                                {line,26}]},
                                                              {lists,map,2,
                                                               [{file,
                                                                 "lists.erl"},
                                                                {line,1239}]},
                                                              {gradualizer_prelude_parse_trans,
                                                               replace_get_modules_and_forms,
                                                               1,
                                                               [{file,
                                                                 "/Users/aleksanderlisiecki/Documents/Github/Gradualizer/src/gradualizer_prelude_parse_trans.erl"},
                                                                {line,10}]},
                                                              {gradualizer_prelude_parse_trans,
                                                               replace_get_modules_and_forms,
                                                               1,
                                                               [{file,
                                                                 "/Users/aleksanderlisiecki/Documents/Github/Gradualizer/src/gradualizer_prelude_parse_trans.erl"},
                                                                {line,15}]},
                                                              {compile,
                                                               '-foldl_transform/3-anonymous-2-',
                                                               3,
                                                               [{file,
                                                                 "compile.erl"},
                                                                {line,1147}]},
                                                              {compile,
                                                               foldl_transform,
                                                               3,
                                                               [{file,
                                                                 "compile.erl"},
                                                                {line,1150}]},
                                                              {compile,
                                                               '-internal_comp/5-anonymous-1-',
                                                               3,
                                                               [{file,
                                                                 "compile.erl"},
                                                                {line,396}]}]}

make: *** [escript] Error 1
```
and it fails as pasted above. Am I doing something wrong?

snippet step by step:

```
git clone https://github.com/josefs/Gradualizer
cd Gradualizer/
make escript
```

**Comment by Zalastax** [comment]
I don't think you're doing anything wrong. I've seen the same error. I don't know what the issue is. We've had other problems with rebar3 so we are considering going back to Make.

**Comment by zuiderkwast** [comment]
I think some modules need to be compiled first. The parse transform and any modules used by it need to be compiled before the module using the parse transform.

**Comment by zuiderkwast** [comment]
We should make sure compiling works with rebar even if we will use something else during development, because we want to support rebar as a tool/plugin/dependency/etc.

From the sample rebar config file:
```
%% Erlang files to compile before the rest. Rebar automatically compiles
%% parse_transforms and custom behaviours before anything other than the files
%% in this list.
{erl_first_files, ["src/mymib1.erl", "src/mymib2.erl"]}.
```

Thus, it could be a good idea to make sure the parse transform doesn't have any dependencies apart from OTP. I think it can be achieved easily by using `epp` directly rather than our wrapper function for it.

**Comment by KennethL** [comment]
I think the use of a parse transform should be avoided. In general I think
you should avoid parse transforms (because of the problems you get here )
and in this case it does not add anything but confusion (making it harder
to understand the code). Since the only use of the parse transform is in
the gradualizer_prelude.erl I think it is pointless. If you want to
generate the module gradualizer_prelude.erl you can do that in a more
straight forward manner with almost the same code as in the parse transform
but driven by the build process explicitly invoking the generation of the
module.
And as the only thing gradualizer_prelude is doing is to populate a db with
data this population can even be done directly from a generated data file
or the whole generation from the overridden module/type/specs can be done
upon initialization of gradualizer possibly checking if there already is a
prepared data file generated (cached) from a previous run.
We have similar solutions in other parts of OTP where we generate modules
based on external data. In for example stdlib we are generating a module
called unicode_util.erl but we
are using makefiles and then it is simple. Don't know if it is easy to do
with rebar3 but I really hope so. Otherwise we have to add that to rebar3.

/Kenneth

**Comment by aleklisi** [comment]
@zuiderkwast so which modules do I need to compile first?

**Comment by Zalastax** [comment]
The reason we are considering moving away from rebar3 is that it behaves weirdly. Both I and @josefs have had problems where we don't get the artifact we expect when running rebar3, probably due to some cache or filesystem issues. I've resigned to always deleting the _build directory before compiling. I also have several issues open (4 towards rebar3 and 1 towards relx) which are not really moving anywhere. Adding it all up, I've sort of lost trust in rebar3.

@aleklisi gradualizer_file_utils 😺

**Comment by zuiderkwast** [comment]
@KennethL The reason we want to include all the data in the BEAMs is that when we build a self-contained escript, we haven't managed to put data files in the zip and to get them out at runtime. It should be possible using the `zip` module but I haven't gotten it to work, even if I generate the escript using the same zip module. The code loader works though and I think it is using another zip implementation (if I remember the source code correctly). I suspect there is some bug in `zip`. I hope I can look into this again because it would be a better solution.

**Comment by aleklisi** [comment]
@Zalastax after adding `{erl_first_files, ["src/gradualizer_file_utils.erl"]}.` to rebar.config . in gradualizer it worked like magic :O

**Comment by aleklisi** [comment]
@Zalastax I created PR that makes includes suggested solution :)
https://github.com/josefs/Gradualizer/pull/197

**Comment by zuiderkwast** [comment]
@aleklisi Ah, that PR is not necessary since the commit I added half an hour ago. Good effort though!

**Comment by aleklisi** [comment]
@zuiderkwast oh didn't notice that :'(
Do you think my PR can still be counted for `hacktoberfest`? ;)

**Comment by zuiderkwast** [comment]
@aleklisi Sure!

**Comment by aleklisi** [comment]
@zuiderkwast thanks :D

**Comment by aleklisi** [comment]
I shall close the issue as it's solved :)
