### ISSUE TITLE
Infinite loop when checking call from gradualizer_type:abstract_expr()

### ISSUE THREAD

**Issue by Zalastax** [josefs/Gradualizer#231]
Checking this causes Gradualizer to hang:
```Erlang
-spec describe_expr(gradualizer_type:abstract_expr()) -> io_lib:chars().
describe_expr({call, _, _, _})            -> "function call".
```

This is the cause of Travis running out of memory in #230.

**Comment by zuiderkwast** [comment]
Because `abstract_expr()` is a very large type and also a recursive type, probably. A gradualizer_cache was introduced already for solving some performance issue, which perhaps can used in more cases. If it's not enough, perhaps we need to do pruning at some point, i.e. stop checking at some maximum depth. But first we need to pinpoint the bottle neck.

**Comment by zuiderkwast** [comment]
I'm not sure it's an infinite loop; just inefficient. The efficient way would be to represent the types on Disjunctive Normal Form, using binary decision trees, as described in *G. Castagna: Covariance and Contravariance: a fresh look at an old issue (a primer in advanced type systems for learning functional programmers* ([contravarianceagain.pdf](https://www.irif.fr/~gc/papers/covcon-again.pdf)) and lifted to gradual types in *G. Castagna and V. Lanvin: Gradual Typing with Union and Intersection Types* ([icfp17.pdf](https://www.irif.fr/~gc/papers/icfp17.pdf)).

**Comment by josefs** [comment]
I've had a look at the first paper that you mentioned @zuiderkwast. This paper uses a pretty big hammer (BDDs and other optimizations) to make testing for subtyping efficient. I think that's overkill for us. But that doesn't mean that there aren't ideas in there that we can use. 

Starting on page 33 the author shows a representation of unions which separates the different types of the unions into buckets so that, for instance, atoms would live in their own bucket and lists would live in another bucket. I think if we had different sized tuples live in different buckets then we could speed up typechecking of the example @Zalastax gave above, because the typechecker wouldn't have to go through all tuples in the union, only those with the same size.

**Comment by zuiderkwast** [comment]
Really nice to see that you're following up on this!

Yes! Keeping them separate and in particular storing tuples by size sounds like a good idea! We'd have to change the code in all the places where we pattern match on unions.

Another thing they do in that paper is lazy unions.

Another thing we could do is to add caching in `subtype/3` and/or `normalize/2` as we have in `glb/3`. (Caching without copying can be done using the process dictionary instead of an ETS table. Not sure if it's worth the ugliness.)

**Comment by erszcz** [comment]
The original code is now tested against as https://github.com/josefs/Gradualizer/blob/e57106f4edb1a17288100f776e6c1c190920ec23/test/should_pass/minimised_gradualizer_fmt.erl and is checked correctly one the current master branch.
