### ISSUE TITLE
Intersection with any()

### ISSUE THREAD

**Issue by Zalastax** [josefs/Gradualizer#232]
There's lots of interesting discussions in https://github.com/josefs/Gradualizer/pull/206#discussion_r335621822 and I want to bring some of that out to a separate issue. In particular, I want to discuss the meaning of intersection with `any()`.

To summarize, @josefs argues that "`any() & integer()` is the same as `integer()`" whereas @zuiderkwast argues that "`any() & integer()` is not the same as `integer()`".

My personal take is that I agree with @zuiderkwast. To me, `T :: any() & integer()` means that `T` is of unknown type but it's at least an `integer()`. If we have `-spec f(5) -> integer().`, I believe that @josefs disallows `f(T)` whereas @zuiderkwast and I don't. My intuition is that `any()` behaves in the same manner as a new type variable (which in this example would be satisfied if it's type is `5`). I think you told me this was wrong during our last fika but I didn't follow. An example for why this thinking gets us to the wrong place would be very helpful!

As an extension to my thinking, I believe that if we also have `-spec g(6) -> integer()`, then we should be allowed to reject `f(T), g(T)` since `T` can't be both `5` and `6`. 

Relevant papers (I believe that the first few pages deal with this issue already):
https://www.irif.fr/~gc/papers/icfp17.pdf
https://www.irif.fr/~gc/papers/popl19.pdf

**Comment by gomoripeti** [comment]
I did not follow the discussion, but for me also `any & integer()` _feels_ like an "unknown subset of all integers". But even if intersection with `any()` should not mean this, I think there would be value if internally Gradualizer could represent such notion, ie "an unknown subtype of a static type" or rather "a dynamic type that is although unknown, it is not a subtype of anything else than a <static type>".  This way Gradualizer could represent a partial information about a type. Sorry about the sidetrack.

**Comment by zuiderkwast** [comment]
@josefs
> The reason I ask is because your ideas sound compelling. They are also different from the existing literature: https://www.irif.fr/~gc/papers/icfp17.pdf which makes them extra intriguing. And I don't think your ideas are necessarily wrong just because they're different from a published paper.

No need. The paper exactly confirms my ideas.

> Let me just give a tldr of the paper: any() & integer() is the same as integer() and any() | integer() is any().

This statement is completely wrong. I suggest you actually read the paper instead guessing. It explains "my ideas" pretty well.

**Comment by josefs** [comment]
Yeah, I need to read the paper properly. It's on my todo list.

**Comment by zuiderkwast** [comment]
Good. :-) Sorry for being harsh!

**Comment by josefs** [comment]
Ok, I've finally read the paper in some detail (at least the initial parts that are relevant to us). You are indeed right, @zuiderkwast. To rephrase the example by @Zalastax , the `integer() & any()` is indeed different from `integer()` in that `integer() & any()` is a compatible subtype of the singleton type `5` whereas `integer()` is not. This follows from the set theoretic semantics of types and the existential predicate lifting of the subtyping relation.

Now, I think we already implement the semantics of intersection and union types that the paper lays out. I was up last night to sketch out some proofs that our typechecking rules actually implement the semantics. Though if someone has a counterexample, I'd be interested in seeing that.

The paper defines the rules for subtyping very differently than we do though. They compute a normal form for types, and that's important to them because they deal with negation types, which are tricky to handle in any other way. But we shouldn't use the normal form because 1) we don't have to 2) it can blow up the sizes of the types enormously. 

But this ticket is not really about the representation of types, but rather about convincing me that I was wrong :-) I think we're all in agreement then. I'll close this ticket. Reopen if you want to continue the discussion.

**Comment by zuiderkwast** [comment]
Really nice to see this! Yeah, now we agree about the paper. :-)

For unions, we're matching the paper by not throwing away `integer()` when normalizing `integer() | any()`. There's a test case for this: [union_with_any.erl](https://github.com/josefs/Gradualizer/blob/master/test/should_fail/union_with_any.erl).

For intersections though, we don't. `GLB` returns `any()` if either type is `any()`. See https://github.com/josefs/Gradualizer/blob/master/src/typechecker.erl#L419 . I'm adding a known problem test for this in PR #266.

IMO, we don't really need this interpretation of intersection with any. It just gives us more precision, especially in type refinement.

I think negation types could add a tiny little bit of precision to exhaustiveness and clause-can't-be-reached checking although these are probably very unlikely cases, so I'm not saying we should add it. Anyway, here's an example where the pattern can be refined to `atom() \ a` after the 1st clase:

```Erlang
-spec refine_me_using_neg_types(atom()) -> ok;
refine_me_using_neg_types(a) -> ok;
refine_me_using_neg_types(a) -> ok; % Error: this clause can never match.
refine_me_using_neg_types(_) -> ok. 
```

Regarding the representation of types, let's talk about it in #231 "infinite loop ...".
