### ISSUE TITLE
Create a gitter

### ISSUE THREAD

**Issue by FrankBro** [josefs/Gradualizer#243]
https://gitter.im/

Since I'm trying to typecheck a fairly large project we have at work, I had to make a few changes to support some of our cases. I've made a couple PRs already and I have a couple more planned. I would love to have a place to discuss with the other people who have been very helpful with my PRs to have a more direct/interactive session. While I could create the room, there is an option to create one for a github repositories that links directly to the project. It seems that only the owner can create it via that options. @josefs, could you create it? All you have to do is:

* Press the + in the bottom left
* Select "create community"
* Click "do you want to start a community for one of your github projects"
* Select the project

**Comment by josefs** [comment]
I've never heard of gitter before but it looks nice. However, I still hesitate to add this because I already have too many channels of communication, e.g. mail, facebook, messenger, whatsapp, reddit, etc., plus all the stuff I use at work. I don't want to have to add yet another channel that I have to check regularly. If there is a way to get gitter to send information to one of my existing channels I'd be more willing to add it but I couldn't find any information about how to do that (I might have missed it though, I only skimmed the docs). 

Do other contributors think this looks like a good way to communicate? @zuiderkwast, @Zalastax, @gomoripeti, what do you think?

**Comment by zuiderkwast** [comment]
I agree with @josefs: If I get notifications by email, than gitter can be OK. I'm not sure we are active enough and many enough to keep a chat room alive though. It's not very fun to write in a chat where nobody answers for a month or two.

I think the github issues are fine, as long as new topics are moved to their own issues. Then it's easy to keep the discussions separate even if there are weeks between each message.

**Comment by Zalastax** [comment]
I do like gitter and you can get email notifications. Unfortunately, I don't think the chat room would be very occupied so in most cases you won't get quick replies. I would say that you should instead feel free to write short messages in issues as if it was a chat room.
