### ISSUE TITLE
Missing included path and function signature being present or not.

### ISSUE THREAD

**Issue by FrankBro** [josefs/Gradualizer#291]
```erlang
% include/test.hrl
-define(ZERO, 0).
```

```erlang
-module(test).

-include("test.hrl").

-spec test1(integer()) -> bool().
test1(I) -> test2(I).

-spec test2(integer()) -> bool().
test2(I) ->
    I < ?ZERO.
```

Depending on how you invoke gradualizer for this, you will get a success or not. The cases are like so:

| `-I include` | `-spec test2...` present | Result |
| - | - | - |
| True |  True | No error |
| True | False | No error |
| False |  True | No error |
| False | False | `Call to undefined function test2/1 on line 6 at column 13` |

Funny enough, if you check the output of `epp`, you see an error within the body of `test2` for the error case: makes sense, the macro `?ZERO` is undefined.

Does the error make sense? The function _IS_ defined in there but the body fails. There's no function signature anyway ... shouldn't we just expect `any()` anyway?

What's the best way to fix this?

**Comment by zuiderkwast** [comment]
## How Gradualizer should handle the error

The reported error is very confusing, indeed. I think we should not typecheck at all if the include files can't be found. Epp returns an error tuple where the `-include` directive was if the file wasn't found. If the list of forms contains any error, we should abort IMO.

There is a simple way to catch this error and other errors such as function clauses in the wrong order and various other things which currently confuses Gradualizer. That is to call **`compile:forms(Forms, [basic_validation, return_errors, return_warnings])`**. It has been suggested before, but Josef thought that it might have a performance impact. I don't think so though. It's a simple pass and it solves a lot of problems.

## How to gradualize from source code when you don't have the right `-I` flags to use

You need the same `-I` flags as for compiling. Since it's very hard to know which `-I` flags are necessary to complile an erl file in the general case (e.g. a project might have complicated structures of make files and building up variables to compose the list of `-I` flags which are passed to `erlc`) the best way to run Gradualizer in this case is to make sure the modules are compiled with `debug_info` and then gradualize the beam files.

**Comment by josefs** [comment]
First of all, sorry for going awol on this project and not responding to notifications. The whole covid thing has been rough for me. 

> That is to call compile:forms(Forms, [basic_validation, return_errors, return_warnings]). It has been suggested before, but Josef thought that it might have a performance impact. I don't think so though. It's a simple pass and it solves a lot of problems.

I don't recall this discussion but if it solves a lot of problems I think it's worth running some numbers and perhaps prove me wrong. I'm willing to be convinced. It'd be useful for me to understand exactly what would be solved by calling `compile:forms()`. Perhaps open a separate ticket for that where we can discuss it, if you'd like to pursue it.

**Comment by zuiderkwast** [comment]
Errors detected with compile's `basic_validation`:
* `-include` file not found (this issue)
* `-spec` for non-existing function
* Arity mismatch between spec and function definition, e.g.
   ```Erlang
    -spec bar() -> ok.
    bar(_) -> ok.
   ```
* "head mismatch", e.g.
    ```Erlang
    foo(_) -> ok; % <-- note the semicolon
    bar(_) -> ok.
    ```
* Use of undefined macros
* Use of undefined records, types and functions (local within the module)

**Comment by zuiderkwast** [comment]
Good to see you @josefs!

**Comment by josefs** [comment]
Thanks! That's a really useful breakdown of the advantages.
