### ISSUE TITLE
Place to chat

### ISSUE THREAD

**Issue by tsloughter** [josefs/Gradualizer#316]
I was looking through the readme and wiki and searching channels on Erlang slack and not finding any place dedicated to discussing Gradualizer.

So first question is, am I missing it and there is a slack or irc channel somewhere? If not, should one be created?

I was hoping to be able to ask some questions that aren't necessarily issues so not wanting to clog the github Issues with them.

**Comment by ilya-klyuchnikov** [comment]
Yep,- Github has recently introduced "Discussions" - "Forums for project". @josefs  - what would you say about enabling it for Gradualizer?

**Comment by josefs** [comment]
Yes, this sounds like a good idea. I haven't heard about github discussions before but that sounds like a nice way to enable more informal discussions. 

For the record, we had a discussion before about other forms of chat/forums/whatnot in #243 and I was against it because it would add yet another channel of communication to keep track of. But having the discussions on an existing channel is quite sensible and github is the perfect place for that.

**Comment by josefs** [comment]
Ok, discussions have now been enabled on this repository.
