### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by josefs** [josefs/Gradualizer#41]
We have a decent test suite. It's be nice to leverage this by adding CI support. I have good experience with travis-ci but I'm interested in 

We also have the possibility to run dialyzer if we implement CI support. Do people think that would be a good idea? I personally think it's be good to keep Gradualizer free from dialyzer warnings, but I'm too lazy to run it frequently. However, @gomoripeti runs it every now and again and finds useful improvements.

**Comment by gomoripeti** [comment]
I usually run `make check` which includes `test`, `dialyze` and `gradualize` (because it's much easier to type, I especially have issues with dialyzer :) ) Unfortunately self-gradualizer currently crashes, so that should be excluded on CI for now. OTOH would be good to have a coverage report either in the log as plain text or exported to some fancy service like coveralls.io

**Comment by gomoripeti** [comment]
As of master 0c702abb7ad6c8f510177973f4c45294bbc73350 self-gradualizing does not crash any more 🎉 so can be included in the CI as a crash-test.

**Comment by Zalastax** [comment]
It seems like it's easier to get code coverage reports if rebar3 is used: https://erlang.mk/guide/coverage.html, https://www.rebar3.org/docs/running-tests#section-code-coverage

**Comment by Zalastax** [comment]
Or maybe not: https://github.com/ninenines/erlang.mk/blob/master/plugins/cover.mk @zuiderkwast care to chime in?
