### ISSUE TITLE
Timeout checking function (performance issue related to jsx?)

### ISSUE THREAD

**Issue by jesperes** [josefs/Gradualizer#449]
I'm seeing a lot of `Timeout checking function` around in our code base:
```
./_build/test/lib/kafka_consumer_util/ebin/kafka_consumer_message.beam: Timeout checking function decode_json/1 on line 27
This is most likely a bug in Gradualizer.
Please report it at https://github.com/josefs/Gradualizer/issues
```
The only common pattern is that the functions mentioned in these errors all seem deal with either JSON or Avro data (using `jsx` or `erlavro`), at least the ones I have investigated a bit deeper. Could the rather large-ish type specs in those applications be causing Gradualizer performance issues?

**Comment by jesperes** [comment]
Actually, I managed to reproduce it with a smaller example:
```erlang
-module(foo).
-export([decode_json/1]).
-spec decode_json(Json::binary()) -> jsx:json_term() | {error, Reason::atom()}.
decode_json(Json) ->
  jsx:decode(Json, []).
```
The problem disappears if I remove the spec, so presumably it is the `jsx:json_term()` type which is causing problems.

**Comment by jesperes** [comment]
I increased the `?form_check_timeout_ms` timeout to 10 minutes, and let it run, and it just sat there spinning for 10 minutes. :(

**Comment by erszcz** [comment]
There's a known, but unsolved, issue with recursive types. The timeout is there to terminate early on a problematic form and keep processing subsequent forms instead of looping indefinitely. This has a huge impact on the UX when editing with Gradualizer hooked via ErlangLS - instead of the ErlangLS VM starting to hog CPU, we get an error, and Gradualizer continues with other functions in the module.

The problematic type here seems to be https://github.com/talentdeficit/jsx/blob/1d3407aa9752430ec0a06111ac1b046ffafdca22/src/jsx.erl#L44-L51.

[`io_lib:chars()` from OTP](https://github.com/erlang/otp/blob/26e886960be3358c4c9adbb705c52043ea096f67/lib/stdlib/src/io_lib.erl#L97) is another example.

I spent quite a long while trying to nail down all the cycles in Gradualizer, with some successes, but some are still lingering there :|

**Comment by erszcz** [comment]
Correction, `io_lib:chars()` does not seem to cause trouble anymore. It seems it's handled properly thanks to the cycle fixes already on the master branch.

**Comment by jesperes** [comment]
Is there a plan to fix this? If it is known that Gradualizer cannot handle recursive types, it would be better to just ignore them (or leave it as an option to the user.) The current situation is a bit suboptimal, as the timeout is reported as a internal bug in Gradualizer.

Something like 
> Gradualizer does not support recursive types. Use --no_warn_recursive_types to suppress this error message.

**Comment by erszcz** [comment]
> If it is known that Gradualizer cannot handle recursive types, it would be better to just ignore them (or leave it as an option to the user.)

Suppressing the warning if a certain flag is present makes sense, I think we could have that. @zuiderkwast WDYT?

**Comment by zuiderkwast** [comment]
I don't think we should focus on adding flags disable parts of the type system. Only if we give up and decide that we can't solve the bug, we can do it IMHO.

**Comment by erszcz** [comment]
@jesperes this should be solved now, finally :) I'm pretty sure there's more to come in these >2 million lines of kred, but let's tackle it step by step :D

**Comment by erszcz** [comment]
With #458 the infinite loops and `Timeout checking function...` should be completely gone. @jesperes could you confirm if that's the case in your codebase?
