### ISSUE TITLE
Vim integration through Neomake

### ISSUE THREAD

**Issue by erszcz** [josefs/Gradualizer#48]
I've started work on integrating Gradualizer with Vim.

![Vim/Neomake showing Gradualizer hints](https://s3.amazonaws.com/uploads.hipchat.com/15025/1268738/6Ka3fYr7X0LbRCQ/Screen%20Shot%202018-10-11%20at%2014.45.11.png)

A Neomake maker runs the `gradualizer` EScript to obtain results for a file open in the current Vim buffer. The code path is extended with per-project `ebin` dirs, so that the analysis results are relatively accurate.

For now, the changes are available below - it still requires some polishing, so I'm not creating PRs yet:
- https://github.com/erszcz/Gradualizer/tree/vim-integration
- https://github.com/erszcz/neomake/tree/erlang-gradualizer

One thing that popped up in Gradualizer output is that line numbers are not placed consistently - I had to add a shell script to reformat them - that's the only change on the `vim-integration` branch above.

@josefs do you think this could be addressed directly in Gradualizer (likely `gradualizer_cli.erl`)? A format like this would be ideal (with _on line 102_ being redundant, but it doesn't hurt):

```
src/docsh_lib.erl:102: The type beam_lib:beam/0 on line 102 is not exported
src/docsh_lib.erl:114: The tuple on line 114 does not have type docsh_beam:debug_info() | false
```

**Comment by Zalastax** [comment]
Great initiative!
I think it would be even better if we supported gathering up the errors as a list- then you could use that directly instead of parsing the errors as text.

By the way, does vim work with sourcer? I would love it if we could get great support in many editors and I think using a language server is the best way of doing so.

**Comment by erszcz** [comment]
Thanks!

> I also think it would be even better if we supported gathering up the errors as a list

Indeed, that would be convenient for integration on the Erlang level.

> By the way, does vim work with sourcer?

Judging by erlang/sourcer#19 it doesn't :/
Integration directly with Neomake is pretty straightforward - enough that I can pull it off singlehandedly in a reasonable amount of time.
While I understand the benefits of a language server, I also have the impression that the learning curve might be a lot steeper (not just the server structure / extension points, but possibly also async jobs on Vim side - I'm a long time user, but a Vimscript newbie).

**Comment by josefs** [comment]
This is just wonderful, @erszcz! I think it'd be great if we can add support for this kind of usage. I have spent very little energy and brain cycles on the error messages so I welcome if someone were to make something more useful out of them.

@Zalastax and @gomoripeti, I like your ideas of having a way of getting errors as structured data and not as strings.

A side note: I've been meaning to change the exceptions that are thrown right now, so that the position is always the second position of the tuple, just like the rest of the abstract syntax. It's not a huge improvement but it'd make the interface a little more consistent.

**Comment by erszcz** [comment]
Gradualizer is now one of the diagnostic tools shipped with [Erlang Language Server](https://github.com/erlang-ls/erlang_ls) (though off by default) and that's the preferred method of using it with different editors.
